### ISSUE TITLE
Coverage path not working when the footprint is very small

### ISSUE THREAD

**Issue by Adrianrr94** [uenota/cpp_uav#1] opened 2019-05-22 12:16 UTC
Greetings,
I have been using your ROS service for a project where the drone need to do a coverage path but the footprint will be really small, like 5-6 m (vertical and horizontal).
So, to debug the code, I tried your specify_rect.py to see if the problem was in my code or in your ROS service. 

To do that, I changed the parameters on the specify_rect.py's interface in order to have a small footprint, obtaining as a result that there is a zone without plan as it can be seen in the screenshot.

![Captura de pantalla de 2019-05-22 14-14-18](https://user-images.githubusercontent.com/36573289/58173535-ec6f4100-7c9b-11e9-8172-f4856d51672a.png)

That's exactly the problem I am having in almost all my planification, I believed this is due to the fact that the footprint is small and the area to cover very big. I would like to know how to fix that.

Thanks.

**Comment by uenota** [comment] 2019-05-25 16:13
Thank you for reporting the problem. I will check the code.

However, I have not worked on this project for a long time, so it may take long time to find out the causes.

**Comment by UTWDrones** [comment] 2019-06-03 17:18
Hello @uenota 
Debuging your service ("torres_etal_2016.cpp"), I found out that when the footprint if small and the given polygon to coverage is a triangle the method computeConvexCoverage returns False no matter where the start points is. So the triangle is decomposed and so that, an error occurs.

`// isOptimal is true if computed path is optimal
  bool isOptimal = computeConvexCoverage(polygon, footprintWidth.data, horizontalOverwrap.data, candidatePath);
  if (isOptimal == true)
  {
    // fill "subpolygon" field of response so that polygon is visualized
    res.subpolygons = generatePolygonVector(polygon);
    // set optimal alternative as optimal path
    // see torres et al. 2016 for Optimal Alternative
    res.path = identifyOptimalAlternative(polygon, candidatePath, start);
  }
  else
  {
    std::vector<PointVector> subPolygons = decomposePolygon(polygon);

    // sum of length of all coverage path
    double pathLengthSum = 0;
    // compute length of coverage path of each subpolygon
    for (const auto& polygon : subPolygons)
    {
      PointVector partialPath;
      computeConvexCoverage(polygon, footprintWidth.data, horizontalOverwrap.data, partialPath);
      pathLengthSum += calculatePathLength(partialPath);
    }
    // existsSecondOptimalPath is true if there is at least one coverage that has no intersection with polygon
    // second optimal path is the path that has second shortest sweep direction without any intersection with polygon
    PointVector secondOptimalPath;
    bool existsSecondOptimalPath =
        findSecondOptimalPath(polygon, footprintWidth.data, horizontalOverwrap.data, candidatePath);
    if (existsSecondOptimalPath == true)
    {
      // compute optimal alternative for second optimal path
      secondOptimalPath = identifyOptimalAlternative(polygon, candidatePath, start);

      // if the length of second optimal path is shorter than the sum of coverage path of subpolygons,
      // set second optimal path as the path
      if (pathLengthSum > calculatePathLength(secondOptimalPath))
      {
        // fill "subpolygon" field of response so that polygon is visualized
        res.subpolygons = generatePolygonVector(polygon);

        res.path = secondOptimalPath;
        return true;
      }
    }
    else if (subPolygons.size() < 2)
    {
      // if number of subpolygon is smaller than 2,
      // it means no valid path can be computed
      ROS_ERROR("Unable to generate path.");
      return true;
    }
`
I am not sure this is the part of the code that is making the algorithm to fail, but it maybe the cause.

I look forward to hearing from you.
Thanks.

**Comment by uenota** [comment] 2019-07-19 14:42
@UTWDrones 
Thank you for feedback!
I fixed the issue about `computeConvexCoverage`.

However the issue @Adrianrr94 reported is not fixed yet.
I will continue to investigate the problem.

**Comment by uenota** [comment] 2019-07-19 18:25
@Adrianrr94 
The issue you reported should be fixed in e526ab8ea036795b28ee6f84e12dfdd21439969d.
Could you check if it fixes your issue?

I'm going to close this issue. Please reopen if the problem persists.

**Closed as completed by uenota** 2019-07-19 18:25 UTC
Labels: bug
